<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>callback</title>
</head>

<body>

  <script>
    const getX = () => {
      const x = 100;
    }
    // console.log(x);          // Error

    const getY = () => {
      const y = 100;

      return y;
    }
    const y = getY();
    console.log(y);             // 100

    const one = (ms, callback) => {
      setTimeout(() => {
        const result = '결과값...';
        // return result;     // setTimeout이 받는다

        callback(result);
      }, ms);
      // console.log(result);   // Error
    }
    // const oneResult = result;

    const innerFunc = (x) => {
      console.log('Hello World', x);
    }
    one(2000, innerFunc);
    one(2000, (x) => {
      console.log('Good Moring', x);
    });

    // promise
    const two = (ms) => {
      // resolve => then이 전달한 함수
      // reject => catch가 전달한 함수
      const promise = new Promise((resolve, reject) => {
        if (ms < 1000) reject(new Error('시간이 너무 짧습니다'));
        setTimeout(() => {
          const result = 'Ajax 결과값...'
          resolve({ status: 200, statusText: 'OK', result });
        }, ms)
      });
      return promise;
    }

    two(2000)
      .then((resp) => {
        console.log(resp.result);

        // promise 객체로 포장해서 리턴한다. 이 결과는 다음 then이 받아 처리한다
        return resp.status;
      })
      .then((resp) => {
        console.log(resp)
      })
      .catch((err) => {
        console.error(err)
      });


    // async ~ await ES2017 - 함수로 정의
    // pending => 처리중. 결과를 확인할 수 없음
    // fulfilled => 처리 성공 then 함수 실행
    // rejected => 처리 실패 catch 함수가 실행
    const getPromise = async function () {
      try {
        const resp1 = await two(2000);
        console.log(resp1);

        const resp2 = await two(resp1.status + 3000);
        console.log(resp2)
      } catch (err) {
        console.error(err)
      }
    }

    getPromise();

  </script>

</body>

</html>